-- Схема разбита на два файла (как использует Docker):
--   1) bootstrap-docker.sql — база и учётное приложение (должен совпадать с MYSQL_* в compose)
--   2) tables.sql           — только CREATE TABLE users
--
-- При ручном импорте под MySQL-root: сначала bootstrap-docker.sql, затем:
--   mysql ... mindbase < database/tables.sql
